let shopItemsData = [
  {
    id: "fth1",
    name : "Black Suit",
    gender: "female",
    color:"black",
    type:"polo",
    level: "high",
    price: 459,
    qty:4,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/k1.webp",
  },
  {
    id: "fth2",
    name: "Office Shirt",
    gender: "male",
    color:"blue",
    type:"polo",
    level: "low",
    price: 199,
    qty:4,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/t1.webp",
  },
  {
    id: "fth3",
    name: "Pink frock",
    gender: "female",
    color:"red",
    type:"polo",
    level: "high",
    price: 599,
    qty:4,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/k2.webp",
  },
  {
    id: "fth4",
    name: "Casual Shirt",
    gender: "male",
    color:"black",
    type:"polo",
    level: "medium",
    price: 300,
    qty:4,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/t2.webp",
  },
  {
    id: "fth5",
    name: "Panjabi Gagraa",
    gender: "female",
    color:"blue",
    type:"polo",
    level: "high",
    price: 469,
    qty:4,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/k3.webp",
  },
  {
    id: "fth6",
    name: "Pink -Green",
    gender: "male",
    color:"red",
    type:"polo",
    level: "medium",
    price: 399,
    qty:4,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/t3.webp",
  },
  {
    id: "fth7",
    name: "Tour suit",
    gender: "female",
    color:"black",
    type:"polo",
    level: "high",
    price: 450,
    qty:4,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/k4.webp",
  },
  {
    id: "fth8",
    name: "Polo Shirt",
    gender: "male",
    color:"red",
    type:"polo",
    level: "high",
    price: 499,
    qty:4,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/t4.webp",
  },
  {
    id: "fth9",
    name: "White Grow",
    gender: "female",
    color:"blue",
    type:"polo",
    level: "high",
    price: 850,
    qty:4,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/k5.webp",
  },
  {
    id: "fth10",
    name: "Healty Shirt",
    gender: "male",
    color:"blue",
    type:"polo",
    level: "low",
    price: 120,
    qty:4,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/t5.webp",
  },
  {
    id: "fth11",
    name: "Patiyala Suit",
    gender: "female",
    color:"red",
    type:"polo",
    level: "medium",
    price: 299,
    qty:4,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/k6.webp",
  },
  {
    id: "fth12",
    name: "Fth T-Shirt",
    gender: "male",
    color:"black",
    type:"polo",
    level: "medium",
    price: 350,
    qty:4,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/t6.webp",
  },
];
